[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5173

[[redirects]]
  from = "/api/quiz"
  to = "https://script.google.com/macros/s/AKfycbwuSibl18yUHjWLqSn0fm6oBtXNvf8PA7MVISnEpMU0Rqj8xfZcoYkKN36hYi1iLql_/exec"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200