[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[dev]
  command    = "npm run dev"
  targetPort = 5173

# Proxy all /api/quiz calls to your Netlify Function
[[redirects]]
  from    = "/api/quiz"
  to      = "/.netlify/functions/quiz"
  status  = 200
  force   = true
  headers = { Access-Control-Allow-Origin = "*" }

# Single‐page‐app fallback
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
