# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5173

[[redirects]]
  from = "/api/quiz"
  # Ersätt med din exakta Google Apps Script Web App URL
  to = "https://script.google.com/macros/s/AKfycbwuSibl18yUHjWLqSn0fm6oBtXNvf8PA7MVISnEpMU0Rqj8xfZcoYkKN36hYi1iLql_/exec"
  status = 200
  force = true
  # KORRIGERAD syntax för headers (med dubbla citationstecken)
  headers = { "Access-Control-Allow-Origin" = "*" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
