[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

# ─────── Lokal utveckling ───────
[dev]
  command   = "npm run dev"
  publish   = "dist"
  functions = "netlify/functions"

# ─────── API-proxy ───────
[[redirects]]
  from    = "/api/quiz"
  to      = "/.netlify/functions/quiz"
  status  = 200
  force   = true
  headers = { Access-Control-Allow-Origin = "*" }

# ─────── SPA-fallback ───────
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200