[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5173

[[redirects]]
  from = "/api/quiz"
  to = "https://script.google.com/macros/s/AKfycbxLvdXr5VZ6mMcWeLgH4goicDAKlUl0vICnC0oBpEYvXYapJWNDujRn8-RsmtDQhjFQ/exec"
  status = 200
  force = true
  headers = { "Access-Control-Allow-Origin" = "*" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200