# Kör test-proxy-scriptet automatiskt vid varje push till main
env:
  NODE_VERSION: '18.x'

on:
  push:
    branches:
      - main

jobs:
  test-proxy:
    name: Testa API-proxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: \${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Kör test-proxy
        run: npm run test-proxy
        env:
          CI: true
